# Generated by Django 5.0.6 on 2024-06-10 16:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantprofile',
            name='assistant',
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('NORMAL_USER', 'Normal User')], default='NORMAL_USER', max_length=50),
        ),
        migrations.DeleteModel(
            name='AssistantProfile',
        ),
    ]
